name: Packagist Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: hotaruma/packagist-sync@v1.0.1
        with:
          api-token: ${{ secrets.PACKAGIST_TOKEN }}
  